# Generated by Django 2.2 on 2019-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooklibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historys',
            name='date_borrow',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historys',
            name='date_return',
            field=models.DateField(),
        ),
    ]
