# Generated by Django 2.2 on 2019-04-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooklibrary', '0002_auto_20190426_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20)),
                ('index', models.SmallIntegerField(unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
