# Generated by Django 2.2 on 2019-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooklibrary', '0003_hotimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotimages',
            name='img',
            field=models.ImageField(upload_to='hotimages'),
        ),
    ]
