# Generated by Django 2.2 on 2019-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooklibrary', '0004_auto_20190429_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='headers'),
        ),
    ]
