# Generated by Django 2.2 on 2019-04-29 06:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooklibrary', '0005_users_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
