# Generated by Django 2.2 on 2019-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_comment_num',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
