# Generated by Django 2.2 on 2019-04-19 09:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            managers=[
                ('gdmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
